### ISSUE TITLE
Minor Documentation error: /> should be >

### ISSUE THREAD

**Issue by BillMeyerRSA** [stanlemon/javascript#100]
Minor Documentation error: /> should be >
`<Authentication
  url="http://localhost:5984"
  login={<Login />}
  signup={<SignUp />}
/>
  <h1>Authenticated!</h1>
</Authentication>`

should be 

`<Authentication
  url="http://localhost:5984"
  login={<Login />}
  signup={<SignUp />}
>
  <h1>Authenticated!</h1>
</Authentication>`

**Comment by stanlemon** [comment]
Good catch, thanks! It should be fixed now.
